INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("Espace Saint Michel 1", "7 place Saint Michel", 75005, 48.853093, 2.344228, 210, 2, 1);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("Le Desperao 1", "23 rue des écoles", 75005, 48.848384, 2.348973, 200, 2, 1);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("Mistral 2", "70 avenue du Général Leclerc", 75014, 48.829473, 2.328009, 870, 5, 0);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("MK2 Gambetta 1", "6 rue Belgrand", 75020, 48.864763, 2.399555, 1238, 6, 0);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("Publicis Cinema 2", "133 Avenue des Champs Élysées", 75008, 48.872794, 2.296984, 609, 2, 0);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("Beverley", "14 Rue Ville Neuve", 75002, 48.8701157, 2.348716, 100, 1, 0);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("Gaumont Convention 2", "27, 31 Rue Alain Chartier", 75015, 48.838033, 2.295827, 1078, 6, 0);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("Gaumont Opéra Français 8", "38 Boulevard des Italiens", 75009, 48.871048, 2.334386, 994, 5, 0);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("L'arlequin Panorama", "76 Rue de Rennes", 75006, 48.851278, 2.330648, 595, 3, 1);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("MK2 Grand Palais", "Grand Palais Champs Élysées", 75008, 48.870843, 2.304317, 92, 1, 0);
INSERT INTO theater(name, address, postalCode, latitude, longitude, numberOfSeat, numberOfRoom, artHouse) VALUES ("Nouvel Odéan", "6 rue de l'école de médecine", 75006, 48.850764, 2.341747, 119, 1, 1);

INSERT INTO nationality(countryCode, countryName) VALUES ("USA", "États-Unis");
INSERT INTO nationality(countryCode, countryName) VALUES ("FRA", "France");
INSERT INTO nationality(countryCode, countryName) VALUES ("GBA", "Grande Bretagne");


INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Zootopie", 0, 2016-02-17,"lorempicsum.com/nemo/255/200/1", "USA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Tuche 2 : Le rêve Américain", 0, 2016-02-03,"lorempicsum.com/nemo/255/200/1", "FRA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Vaiana, La légende du bout du monde", 0, 2016-11-30,"lorempicsum.com/nemo/255/200/1", "USA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Rogue One : A Star Wars Story", 0, 2016-12-14,"lorempicsum.com/nemo/255/200/1", "USA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("The Revenant", 0, 2016-02-24,"lorempicsum.com/nemo/255/200/1", "USA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Les Animaux Fantastiques", 0, 2016-11-16,"lorempicsum.com/nemo/255/200/1", "GBA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Deadpool", 0, 2016-02-10,"lorempicsum.com/nemo/255/200/1", "USA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Comme des bêtes", 0, 2016-07-27,"lorempicsum.com/nemo/255/200/1", "USA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Le livre de la Jungle", 0, 2016-04-13,"lorempicsum.com/nemo/255/200/1", "USA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Age de Glace : Les lois de l'univers", 0, 2016-07-13,"lorempicsum.com/nemo/255/200/1", "USA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Le monde de Dory", 0, 2016-06-16,"lorempicsum.com/nemo/255/200/1", "USA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Camping 3", 0, 2016-06-29,"lorempicsum.com/nemo/255/200/1", "FRA");
INSERT INTO movie(title, blackAndWhite, releaseDate, imageLink, nationality) VALUES ("Star Wars : Episode 7, Le réveil de la force", 0, 2015-12-28,"lorempicsum.com/nemo/255/200/1", "USA");

INSERT INTO genre(name) VALUES ("Action");
INSERT INTO genre(name) VALUES ("Thriller");
INSERT INTO genre(name) VALUES ("Comédie");
INSERT INTO genre(name) VALUES ("Romance");
INSERT INTO genre(name) VALUES ("Biopic");
INSERT INTO genre(name) VALUES ("Science-fiction");
INSERT INTO genre(name) VALUES ("Aventure");
INSERT INTO genre(name) VALUES ("Drame");

INSERT INTO movieGenre(idMovie, idGenre) VALUES (7, 3);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (8, 2);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (9, 1);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (10, 2);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (11, 7);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (12, 4);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (13, 4);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (13, 5);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (14, 6);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (14, 1);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (15, 3);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (15, 8);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (16, 5);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (16, 6);
INSERT INTO movieGenre(idMovie, idGenre) VALUES (16, 8);

INSERT INTO movieTheater(idMovie, idTheater) VALUES (4,1);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (5,2);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (6,3);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (7,4);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (8,5);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (9,6);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (10,7);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (11,8);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (12,9);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (13,10);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (14,11);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (15,12);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (16,12);

INSERT INTO movieTheater(idMovie, idTheater) VALUES (4,12);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (5,11);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (6,10);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (7,9);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (8,8);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (9,7);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (10,6);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (11,5);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (12,4);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (13,3);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (14,2);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (15,1);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (16, 6);

INSERT INTO movieTheater(idMovie, idTheater) VALUES (4,6);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (5,5);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (6,4);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (7,3);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (8,2);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (9,1);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (10,4);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (11,9);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (12,8);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (13,11);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (14,10);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (15,10);
INSERT INTO movieTheater(idMovie, idTheater) VALUES (16,3);

INSERT INTO actor(idCast, idMovie, role) VALUES (1, 4, "Iron Man");
INSERT INTO actor(idCast, idMovie, role) VALUES (1, 7, "Star Lord");
INSERT INTO actor(idCast, idMovie, role) VALUES (1, 14, "Captain America");
INSERT INTO actor(idCast, idMovie, role) VALUES (2, 6, "Thanos");
INSERT INTO actor(idCast, idMovie, role) VALUES (2, 10, "Thor");
INSERT INTO actor(idCast, idMovie, role) VALUES (2, 12, "Veuve noire");
INSERT INTO actor(idCast, idMovie, role) VALUES (3, 5, "Docteur Strange");
INSERT INTO actor(idCast, idMovie, role) VALUES (4, 7, "Gamora");
INSERT INTO actor(idCast, idMovie, role) VALUES (4, 8, "Spider Man");
INSERT INTO actor(idCast, idMovie, role) VALUES (4, 3, "Sorcière Noire");
INSERT INTO actor(idCast, idMovie, role) VALUES (5, 8, "Nébula");
INSERT INTO actor(idCast, idMovie, role) VALUES (6, 9, "Oeil de faucon");
INSERT INTO actor(idCast, idMovie, role) VALUES (7, 10, "Bruce Banner");
INSERT INTO actor(idCast, idMovie, role) VALUES (8, 11, "Groot");
INSERT INTO actor(idCast, idMovie, role) VALUES (9, 12, "Drax");
INSERT INTO actor(idCast, idMovie, role) VALUES (9, 13, "Vision");
INSERT INTO actor(idCast, idMovie, role) VALUES (9, 14, "Wong");

INSERT INTO frequenting(year, month, numbersOfEntries, idTheater) VALUES ();